# Generated by Django 4.1.3 on 2022-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0002_receita_pessoa"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="publicada",
            field=models.BooleanField(default=False),
        ),
    ]
